import {
  IconWallet,
  IconShoppingCart,
  IconCash,
  IconCreditCard,
  IconReceipt,
  IconShoppingBag,
  IconCake,
  IconGift,
  IconHome,
  IconBuilding,
  IconSmartHome,
  IconDeviceMobile,
  IconDeviceTv,
  IconBrandSpotify,
  IconMicrophone,
  IconMusic,
  IconCamera,
  IconBrush,
  IconPencil,
  IconBook,
  IconSchool,
  IconTools,
  IconCar,
  IconBike,
  IconPlane,
  IconBus,
  IconPizza,
  IconCoffee,
  IconBottle,
  IconChefHat,
  IconLeaf,
  IconSun,
  IconCloud,
  IconDroplet,
  IconPaw,
  IconHeart,
  IconStar,
  IconDiamond,
  IconTrophy,
  IconMedal,
  IconMoodSmile,
  IconTree,
  IconFish,
  IconRun,
  IconFlame,
  IconHeadphones,
  IconWifi,
  IconBolt,
} from 'tabler-icons-react-native';

export const FINANCE_ICONS = [
  { name: 'Wallet', icon: IconWallet },
  { name: 'ShoppingCart', icon: IconShoppingCart },
  { name: 'Cash', icon: IconCash },
  { name: 'CreditCard', icon: IconCreditCard },
  { name: 'Receipt', icon: IconReceipt },
  { name: 'ShoppingBag', icon: IconShoppingBag },
  { name: 'Cake', icon: IconCake },
  { name: 'Gift', icon: IconGift },
  { name: 'Home', icon: IconHome },
  { name: 'Building', icon: IconBuilding },
  { name: 'SmartHome', icon: IconSmartHome },
  { name: 'Device', icon: IconDeviceMobile },
  { name: 'Tv', icon: IconDeviceTv },
  { name: 'Spotify', icon: IconBrandSpotify },
  { name: 'Microphone', icon: IconMicrophone },
  { name: 'Music', icon: IconMusic },
  { name: 'Camera', icon: IconCamera },
  { name: 'Brush', icon: IconBrush },
  { name: 'Pencil', icon: IconPencil },
  { name: 'Book', icon: IconBook },
  { name: 'School', icon: IconSchool },
  { name: 'Tools', icon: IconTools },
  { name: 'Car', icon: IconCar },
  { name: 'Bike', icon: IconBike },
  { name: 'Plane', icon: IconPlane },
  { name: 'Bus', icon: IconBus },
  { name: 'Pizza', icon: IconPizza },
  { name: 'Coffee', icon: IconCoffee },
  { name: 'Bottle', icon: IconBottle },
  { name: 'Leaf', icon: IconLeaf },
  { name: 'Sun', icon: IconSun },
  { name: 'Cloud', icon: IconCloud },
  { name: 'Droplet', icon: IconDroplet },
  { name: 'Paw', icon: IconPaw },
  { name: 'Heart', icon: IconHeart },
  { name: 'Star', icon: IconStar },
  { name: 'Diamond', icon: IconDiamond },
  { name: 'Trophy', icon: IconTrophy },
  { name: 'Medal', icon: IconMedal },
  { name: 'Smile', icon: IconMoodSmile },
  { name: 'Tree', icon: IconTree },
  { name: 'Fish', icon: IconFish },
  { name: 'Cook', icon: IconChefHat },
  { name: 'Run', icon: IconRun },
  { name: 'Flame', icon: IconFlame },
  { name: 'Headphones', icon: IconHeadphones },
  { name: 'Wifi', icon: IconWifi },
  { name: 'Bolt', icon: IconBolt },
];