import { 
  IconActivity, IconFlame, IconBook, IconCpu, IconDeviceGamepad, 
  IconPalette, IconBrandSpotify, IconMedal, IconCoffee, IconGlassFull, 
  IconBottle, IconMoodSmile, IconBrain, IconRun, IconSwimming, 
  IconYoga, IconBike, IconWalk, IconDumbbell, IconChess, 
  IconCode, IconMusic, IconMicrophone, IconHeadphones, IconCamera, 
  IconBrush, IconPencil, IconWriting, IconBackpack, IconShoppingBag, 
  IconLeaf, IconSun, IconMoon, IconCloud, IconUmbrella, 
  IconPizza, IconChefHat, IconDroplet, IconPlant, IconBuilding, 
  IconHome, IconCar, IconPlane, IconBus, 
  IconFish, IconPaw, IconHeart, IconStar, IconDiamond 
} from 'tabler-icons-react-native';

export const HABIT_ICONS = [
  { name: 'Activity', icon: IconActivity },
  { name: 'Flame', icon: IconFlame },
  { name: 'Book', icon: IconBook },
  { name: 'Cpu', icon: IconCpu },
  { name: 'Gamepad', icon: IconDeviceGamepad },
  { name: 'Palette', icon: IconPalette },
  { name: 'Spotify', icon: IconBrandSpotify },
  { name: 'Medal', icon: IconMedal },
  { name: 'Coffee', icon: IconCoffee },
  { name: 'Glass', icon: IconGlassFull },
  { name: 'Bottle', icon: IconBottle },
  { name: 'Smile', icon: IconMoodSmile },
  { name: 'Brain', icon: IconBrain },
  { name: 'Run', icon: IconRun },
  { name: 'Swimming', icon: IconSwimming },
  { name: 'Yoga', icon: IconYoga },
  { name: 'Bike', icon: IconBike },
  { name: 'Walk', icon: IconWalk },
  { name: 'Dumbbell', icon: IconDumbbell },
  { name: 'Chess', icon: IconChess },
  { name: 'Code', icon: IconCode },
  { name: 'Music', icon: IconMusic },
  { name: 'Microphone', icon: IconMicrophone },
  { name: 'Headphones', icon: IconHeadphones },
  { name: 'Camera', icon: IconCamera },
  { name: 'Brush', icon: IconBrush },
  { name: 'Pencil', icon: IconPencil },
  { name: 'Writing', icon: IconWriting },
  { name: 'Backpack', icon: IconBackpack },
  { name: 'Shopping', icon: IconShoppingBag },
  { name: 'Leaf', icon: IconLeaf },
  { name: 'Sun', icon: IconSun },
  { name: 'Moon', icon: IconMoon },
  { name: 'Cloud', icon: IconCloud },
  { name: 'Umbrella', icon: IconUmbrella },
  { name: 'Pizza', icon: IconPizza },
  { name: 'Chef', icon: IconChefHat },
  { name: 'Droplet', icon: IconDroplet },
  { name: 'Plant', icon: IconPlant },
  { name: 'Building', icon: IconBuilding },
  { name: 'Home', icon: IconHome },
  { name: 'Car', icon: IconCar },
  { name: 'Plane', icon: IconPlane },
  { name: 'Bus', icon: IconBus },
  { name: 'Fish', icon: IconFish },
  { name: 'Paw', icon: IconPaw },
  { name: 'Heart', icon: IconHeart },
  { name: 'Star', icon: IconStar },
  { name: 'Diamond', icon: IconDiamond },
];
