# Generated by Django 6.1.1 on 2026-09-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
