# Generated by Django 6.0.4 on 2026-05-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_journalentry_highlight_alter_journalentry_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='content',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='highlight',
            field=models.TextField(max_length=280),
        ),
    ]
