# Generated by Django 6.0.4 on 2026-05-27 18:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_remove_journalentry_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('user', 'date')},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='energy_score',
            field=models.IntegerField(blank=True, help_text='Energy score from 1-10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='mood_score',
            field=models.IntegerField(blank=True, help_text='Mood score from 1-10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional longer annotations'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='highlight',
            field=models.TextField(help_text='Primary short reflection', max_length=280),
        ),
        migrations.CreateModel(
            name='CustomRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_ratings', to='journal.journalentry')),
            ],
            options={
                'unique_together': {('journal_entry', 'label')},
            },
        ),
        migrations.DeleteModel(
            name='JournalTagRating',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='mood',
        ),
    ]
