# Generated by Django 6.0.4 on 2026-05-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_journalsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalsettings',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='journalsettings',
            name='repeat_days',
            field=models.JSONField(default=list),
        ),
    ]
