# Generated by Django 6.0.4 on 2026-05-27 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_remove_journalsettings_days_of_week_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalsettings',
            old_name='repeat_days',
            new_name='days_of_week',
        ),
        migrations.AddField(
            model_name='journalsettings',
            name='repeat_mode',
            field=models.CharField(choices=[('every_day', 'Every day'), ('selected_days', 'Selected days')], default='every_day', max_length=20),
        ),
        migrations.AlterField(
            model_name='journalsettings',
            name='reminder_time',
            field=models.TimeField(default='20:00:00'),
        ),
        migrations.AlterField(
            model_name='journalsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
