# Generated by Django 6.0.4 on 2026-05-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_rename_repeat_days_journalsettings_days_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalsettings',
            name='default_tags',
            field=models.JSONField(default=list),
        ),
    ]
