# Generated by Django 6.0.6 on 2026-08-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_journalsettings_default_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='highlight',
            field=models.TextField(blank=True, default='', help_text='Primary short reflection', max_length=280),
        ),
    ]
