# Generated by Django 6.1.1 on 2026-09-29 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_alter_journalentry_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='notes',
        ),
    ]
