# Generated by Django 6.0.4 on 2026-04-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='area',
        ),
        migrations.RemoveField(
            model_name='task',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
