# Generated by Django 6.0.4 on 2026-06-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_financeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeentry',
            name='name',
            field=models.CharField(default='Unnamed', max_length=255),
        ),
    ]
