# Generated by Django 6.0.6 on 2026-07-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_financeentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
