# Generated by Django 6.0.6 on 2026-08-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_budgetitem_delete_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetItem',
        ),
    ]
