# Generated by Django 6.0.6 on 2026-08-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_remove_budget_unique_budget_per_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
