# Generated by Django 6.0.6 on 2026-08-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_remove_transaction_account_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
