# Generated by Django 6.0.6 on 2026-08-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_category_color_category_description_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
