# Generated by Django 6.0.6 on 2026-08-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_categoryreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryreminder',
            name='week_of_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryreminder',
            name='day_of_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
