# Generated by Django 6.0.6 on 2026-08-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_categoryreminder_week_of_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
