# Generated by Django 6.0.6 on 2026-08-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_categoryduedate_delete_categoryreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='debt_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_debt',
            field=models.BooleanField(default=False),
        ),
    ]
