# Generated by Django 6.0.4 on 2026-04-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_category_habit_frequency_habit_reminder_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
