# Generated by Django 6.0.4 on 2026-04-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_days_of_week'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='habitlog',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_habit_log_per_day'),
        ),
    ]
