# Generated by Django 6.0.4 on 2026-04-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_remove_habitlog_unique_habit_log_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='icon',
            field=models.CharField(default='Activity', max_length=50),
        ),
    ]
