# Generated by Django 6.0.4 on 2026-04-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_habit_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='has_target',
            field=models.BooleanField(default=False),
        ),
    ]
