# Generated by Django 6.0.4 on 2026-04-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_habit_has_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='target_type',
            field=models.CharField(choices=[('COUNT', 'Count'), ('TIME', 'Time')], default='COUNT', max_length=10),
        ),
    ]
