# Generated by Django 6.0.4 on 2026-04-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_habit_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
