# Generated by Django 6.0.6 on 2026-08-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_habitlog_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
